import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components/sidebar'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="mb-4 flex p-4">
          <div className="w-full max-w-72">
            <Sidebar />
          </div>
          <main className="container mx-auto">{children}</main>
        </div>
      </body>
    </html>
  )
}
