import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Sidebar from './ui/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-50 text-zinc-950 antialiased dark:bg-zinc-950 dark:text-zinc-50`}
      >
        <div className="flex">
          <div className="relative w-full max-w-72">
            <Sidebar />
          </div>
          <div className="mx-auto w-screen max-w-screen-xl px-14 py-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
